version: "2"
run:
  timeout: 5m
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    paths:
      - _test\.go$
linters:
  enable:
    - revive
    - govet
    - unused
    - whitespace
    - misspell
  disable:
    - errcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
  exclusions:
    rules:
      - path: "_test\\.go$"
        linters:
          - staticcheck
          - ineffassign
    paths:
      - .github
      - hack
      - vendor
      - frontend
      - third_party
