services:
  wireguard-ui:
    build: .
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    ports:
      - "5001:5001"
    environment:
      - BIND_ADDRESS=0.0.0.0:5001
      - DISABLE_LOGIN=true
      - WGUI_LOG_LEVEL=DEBUG
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    volumes:
      - ./db:/app/db
    restart: unless-stopped
